### ISSUE TITLE
몬티홀 게임 시뮬레이션 기능 구현

### ISSUE THREAD

**Issue by Perelman-0** [upstage-7/upstage_git_test#3]
## Description
몬티홀 게임을 N회 시행시 시뮬레이션 결과를 출력하는 함수를 짜주세요,

## Tasks
- [ ] 시뮬레이션 횟수 : N회 입력
- [ ] N회에 대한 몬티홀게임을 진행하고 시뮬레이션을 동작시키는 시스템
- [ ] 실제 결과 출력

## References
- [몬티홀 문제 위키피디아 사이트](https://en.wikipedia.org/wiki/Monty_Hall_problem)
